spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    producer:
      bootstrap-servers: kafka.stg.iparking.co.kr:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      properties:
        bootstrap:
          servers: kafka.stg.iparking.co.kr:9092
#    template:
#      default-topic: demo-shyook-library-events
